services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
  nginx:
    image: nginx:stable-alpine
    depends_on: ["backend"]
    ports: ["8080:80"]
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
